model_list: []

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  database_url: os.environ/DATABASE_URL
  store_model_in_db: true
  ui_access_mode: admin_only
  disable_spend_logs: false
  maximum_spend_logs_retention_period: "60d"
  maximum_spend_logs_retention_interval: "1d"

litellm_settings:
  set_verbose: false
  drop_params: true
  telemetry: false
  request_timeout: 600
  num_retries: 2